# -*- coding: utf-8 -*-
"""twtte bit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ySeVu-ev7NP7n4gngWapoQ3HJvwNG8G
"""

import tweepy
from textblob import TextBlob
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

consumerkey="5vJu0kvl9eyXSThbShXJSBOxi"
consumersecret="uXS9SQjodrcW0CxQLDFiCFzSPo4K1K8xUG2K9gISVoO0qLExCM"
accesstoken="1536910863529279489-15sWWsd04Kv2ArXchvehFmhwvWjG3J"
accesssecret="OsysjYvcnHlTyB3KuHFWBXlWNljGWsZMQNxaXOfz3luLY"

authenticated=tweepy.OAuthHandler(consumerkey,consumersecret)
authenticated.set_access_token(accesstoken,accesssecret)
api=tweepy.API(authenticated, wait_on_rate_limit=True)

search_term='#bitcoin -filter:retweets'
tweets = tweepy.Cursor(api.search,q=search_term,lang='en',since='2018-11-10',tweet_mode='extended').items(2000)
all_tweets=[tweet.full_text for tweet in tweets]

df=pd.DataFrame(all_tweets, columns=['Tweets'])
df.head(5)

def cleanTwt(twt):
  twt=re.sub('#bitcoin','bitcoin',twt)
  twt=re.sub('#Bitcoin','Bitcoin',twt)
  twt=re.sub('#[a-zA-z0-9]+','',twt)
  twt=re.sub('\\n','',twt)
  twt=re.sub('https?:\/\/\S+','',twt)
  return twt

df['cleaned_Tweets'] = df['Tweets'].apply(cleanTwt)
df.head(5)

def getSUBjectivity(twt):
  return TextBlob(twt).sentiment.subjectivity
def getPolarity(twt):
  return TextBlob(twt).sentiment.polarity
df["subjectivity"]=df["cleaned_Tweets"].apply(getSUBjectivity)
df["Polarity"]=df["cleaned_Tweets"].apply(getPolarity)


df.head()

def getsentiment(score):
  if score <0:
    return 'Negative'
  elif score==0:
    return 'Neutral'
  else:
    return 'Positive'

df["sentiment"]=df["Polarity"].apply(getsentiment)
df.head()

plt.figure(figsize=(8,6))
for i in range(0,df.shape[0]):
  plt.scatter(df['Polarity'][i],df['subjectivity'][i],color='red')
plt.title('Sentimental graph')
plt.xlabel('Polarity')
plt.ylabel('Subjectivity')
plt.show()

df['sentiment'].value_counts().plot(kind='bar')
plt.title('bar sentiment')
plt.xlabel('Sentiment')
plt.ylabel('nomber')
plt.show()